"""macOS launchd backend for the tick (DESIGN section 13): a per-user LaunchAgent plus a generated ``.sh`` wrapper.

The job, the wrapper's duties and the spec are shared (:mod:`fm.jobs.scheduler_base`); this backend renders them for
macOS:

- The wrapper is ``scripts/espn-fantasy-tick.sh`` under the config dir, run by ``/bin/sh`` so it needs no execute bit
  (it gets one anyway). launchd hands a job a bare ``PATH`` (``/usr/bin:/bin:/usr/sbin:/sbin``), which is why the
  uv path is embedded absolute.
- The agent is ``~/Library/LaunchAgents/local.espn-fantasy-tick.plist`` (:func:`agent_label`), loaded into the
  logged-in user's GUI domain (``launchctl bootstrap gui/<uid>``): the browser profile and the ESPN session belong to
  that user, the same reason the Windows task keeps the interactive token. ``StartInterval`` runs it every
  ``interval_minutes``; ``RunAtLoad`` ticks once at login so a gap is reported straight away; ``ProcessType
  Interactive`` keeps launchd from throttling a tick that is driving a browser before a lock. launchd never starts a
  second copy of a job that is still running (the Windows ``-MultipleInstances IgnoreNew``).
- launchd runs on battery but never wakes a sleeping Mac. A tick missed during sleep runs on wake and reports the
  windows it missed; keeping the Mac awake at locks is a power setting (``pmset``, which needs ``sudo``), so install
  leaves it to the user and says so in a note.

Every ``render_*`` function is pure and :func:`install_agent`, :func:`uninstall_agent` and :func:`show_agent` take an
injectable :class:`Runner`, so tests render the commands and never touch launchd. ``fm schedule`` drives this backend
through :data:`MACOS`.
"""

from __future__ import annotations

import functools
import os
import plistlib
import shlex
import time
from pathlib import Path

from fm.jobs.scheduler_base import (
    Backend,
    Runner,
    RunResult,
    ScheduleReport,
    SchedulerError,
    ScheduleSpec,
)

MACOS_WRAPPER_SUFFIX = ".sh"
LABEL_PREFIX = "local."
"""launchd labels are reverse-DNS by convention; ``local.`` marks a job that belongs to no vendor."""
LAUNCHCTL = "launchctl"
LAUNCHD_LOG_FILENAME = "launchd.log"
"""launchd's own stdout/stderr for the job: what the wrapper printed before its redirect (a failed ``cd``)."""
AGENT_NOT_FOUND_MARKERS = ("could not find service", "no such process", "service is not loaded")
"""Substrings (lower-case) that mean "no such job" in launchctl output."""
SHELL = "/bin/sh"
UNLOAD_WAIT_ATTEMPTS = 20
UNLOAD_WAIT_SECONDS = 0.25
"""``bootout`` returns before launchd has torn the old job down, and a bootstrap in that gap fails with error 5, so a
reinstall polls ``launchctl print`` until the job is gone (at most 5 s)."""

_EXPORT_PREFIX = "export "


# --- where the agent lives --------------------------------------------------------------------------------------------


def launch_agents_dir() -> Path:
    """``~/Library/LaunchAgents``: the per-user agents launchd loads at login."""
    return Path.home() / "Library" / "LaunchAgents"


def current_uid() -> int:
    """The user id whose GUI domain the agent lives in (``os.getuid`` exists only on POSIX)."""
    getuid = getattr(os, "getuid", None)
    if getuid is None:
        raise SchedulerError("launchd needs a POSIX user id; this backend runs on macOS only")
    return int(getuid())


def agent_label(spec: ScheduleSpec) -> str:
    return f"{LABEL_PREFIX}{spec.task_name}"


def plist_path(spec: ScheduleSpec) -> Path:
    return launch_agents_dir() / f"{agent_label(spec)}.plist"


def _domain() -> str:
    return f"gui/{current_uid()}"


def _service(spec: ScheduleSpec) -> str:
    return f"{_domain()}/{agent_label(spec)}"


# --- rendering --------------------------------------------------------------------------------------------------------


def render_wrapper_sh(spec: ScheduleSpec) -> str:
    """Text of the ``.sh`` wrapper (LF line endings): cd to the repo, export env, run the tick, append to the log."""
    log = shlex.quote(str(spec.log_path))
    lines = [
        "#!/bin/sh",
        "# Generated by `fm schedule install`; do not edit, re-run install instead.",
        f"cd {shlex.quote(str(spec.repo_root))} || exit 1",
        *[f"{_EXPORT_PREFIX}{key}={shlex.quote(value)}" for key, value in spec.env().items()],
        f"mkdir -p {shlex.quote(str(spec.logs_dir))}",
        f"echo \"[$(date '+%Y-%m-%d %H:%M:%S')] tick start\" >> {log}",
        f"exec {shlex.join(spec.argv())} >> {log} 2>&1",
    ]
    return "\n".join(lines) + "\n"


def agent_wrapper_env(path: Path) -> dict[str, str]:
    """The ``export KEY=VALUE`` lines of a generated wrapper (what the scheduled tick will see)."""
    env: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line.startswith(_EXPORT_PREFIX):
            continue
        words = shlex.split(line[len(_EXPORT_PREFIX) :])
        if len(words) == 1 and "=" in words[0]:
            key, value = words[0].split("=", 1)
            env[key] = value
    return env


def render_plist(spec: ScheduleSpec) -> bytes:
    """The LaunchAgent plist (XML): the wrapper every ``interval_minutes``, once at login, unthrottled."""
    launchd_log = str(spec.logs_dir / LAUNCHD_LOG_FILENAME)
    agent = {
        "Label": agent_label(spec),
        "ProgramArguments": [SHELL, str(spec.wrapper_path)],
        "WorkingDirectory": str(spec.repo_root),
        "StartInterval": spec.interval_minutes * 60,
        "RunAtLoad": True,
        "ProcessType": "Interactive",
        "StandardOutPath": launchd_log,
        "StandardErrorPath": launchd_log,
    }
    return plistlib.dumps(agent, fmt=plistlib.FMT_XML, sort_keys=False)


def render_launchctl_enable(spec: ScheduleSpec) -> list[str]:
    """Clears a ``launchctl disable`` left from before, which would make the bootstrap fail."""
    return [LAUNCHCTL, "enable", _service(spec)]


def render_launchctl_bootstrap(spec: ScheduleSpec) -> list[str]:
    return [LAUNCHCTL, "bootstrap", _domain(), str(plist_path(spec))]


def render_launchctl_bootout(spec: ScheduleSpec) -> list[str]:
    return [LAUNCHCTL, "bootout", _service(spec)]


def render_launchctl_print(spec: ScheduleSpec) -> list[str]:
    return [LAUNCHCTL, "print", _service(spec)]


def is_agent_missing(result: RunResult) -> bool:
    text = result.output.lower()
    return not result.ok and any(marker in text for marker in AGENT_NOT_FOUND_MARKERS)


def render_agent_plan(spec: ScheduleSpec) -> list[str]:
    """What :func:`install_agent` would do, as lines, for ``fm schedule install --dry-run``."""
    lines = [f"wrapper {spec.wrapper_path}:"]
    lines.extend(f"  {line}" for line in render_wrapper_sh(spec).splitlines())
    lines.append(f"agent {plist_path(spec)}:")
    lines.extend(f"  {line}" for line in render_plist(spec).decode("utf-8").splitlines())
    lines.append("commands:")
    for argv in (render_launchctl_bootout(spec), render_launchctl_enable(spec), render_launchctl_bootstrap(spec)):
        lines.append("  " + shlex.join(argv))
    return lines


# --- actions ----------------------------------------------------------------------------------------------------------

WAKE_NOTE = (
    "launchd does not wake a sleeping Mac: a tick missed during sleep runs on wake and reports the windows it missed. "
    "Keep the Mac awake at locks (System Settings > Battery > Options, or sudo pmset)"
)


def _report(action: str, spec: ScheduleSpec) -> ScheduleReport:
    return ScheduleReport(action=action, task_name=agent_label(spec), backend="macos", unit="agent")


def install_agent(spec: ScheduleSpec, runner: Runner) -> ScheduleReport:
    """Write the wrapper and the plist, unload an older copy, then load the agent. Raises :class:`SchedulerError`
    when the bootstrap fails; a failed ``enable`` is a note (the bootstrap reports a disabled job itself)."""
    report = _report("install", spec)
    spec.scripts_dir.mkdir(parents=True, exist_ok=True)
    spec.logs_dir.mkdir(parents=True, exist_ok=True)
    wrapper = spec.wrapper_path
    wrapper.write_text(render_wrapper_sh(spec), encoding="utf-8", newline="\n")
    wrapper.chmod(0o755)
    report.files.append(wrapper)
    plist = plist_path(spec)
    plist.parent.mkdir(parents=True, exist_ok=True)
    plist.write_bytes(render_plist(spec))
    report.files.append(plist)

    bootout = render_launchctl_bootout(spec)
    report.commands.append(bootout)
    if runner(bootout).ok:  # replacing a loaded agent; one never loaded answers "no such process", which is fine
        _wait_unloaded(spec, runner, report)
    enable = render_launchctl_enable(spec)
    report.commands.append(enable)
    enabled = runner(enable)
    if not enabled.ok:
        report.notes.append(f"{agent_label(spec)}: launchctl enable failed ({enabled.output or enabled.returncode})")
    bootstrap = render_launchctl_bootstrap(spec)
    report.commands.append(bootstrap)
    result = runner(bootstrap)
    if not result.ok:
        raise SchedulerError(f"launchctl bootstrap {agent_label(spec)} failed ({result.returncode}): {result.output}")
    report.installed = True
    report.notes.append(WAKE_NOTE)
    return report


def _wait_unloaded(spec: ScheduleSpec, runner: Runner, report: ScheduleReport) -> None:
    argv = render_launchctl_print(spec)
    for attempt in range(UNLOAD_WAIT_ATTEMPTS):
        if is_agent_missing(runner(argv)):
            if attempt:
                report.commands.append(argv)
            return
        time.sleep(UNLOAD_WAIT_SECONDS)
    report.commands.append(argv)
    report.notes.append(f"{agent_label(spec)}: still unloading after bootout; the bootstrap may fail, re-run install")


def uninstall_agent(spec: ScheduleSpec, runner: Runner) -> ScheduleReport:
    """Unload the agent (a missing one is not an error) and remove the plist and the wrapper."""
    report = _report("uninstall", spec)
    argv = render_launchctl_bootout(spec)
    report.commands.append(argv)
    result = runner(argv)
    if not result.ok:
        if is_agent_missing(result):
            report.notes.append(f"{agent_label(spec)}: not loaded")
        else:
            raise SchedulerError(f"launchctl bootout {agent_label(spec)} failed ({result.returncode}): {result.output}")
    for path in (plist_path(spec), spec.wrapper_path):
        if path.exists():
            path.unlink()
            report.files.append(path)
    return report


def show_agent(spec: ScheduleSpec, runner: Runner) -> str:
    """``launchctl print`` for the agent plus the plist and what the wrapper sets. Never raises."""
    label = agent_label(spec)
    try:
        result = runner(render_launchctl_print(spec))
    except SchedulerError as exc:
        return f"{label}: cannot query launchd ({exc})\n{_file_lines(spec)}"
    if result.ok:
        return result.stdout.strip() + "\n" + _file_lines(spec)
    if is_agent_missing(result):
        return f"{label}: not installed (fm schedule install)\n{_file_lines(spec)}"
    return f"{label}: error ({result.returncode}): {result.output}"


def _file_lines(spec: ScheduleSpec) -> str:
    plist = plist_path(spec)
    lines = [f"Plist:                                {plist}{'' if plist.is_file() else ' (not written)'}"]
    wrapper = spec.wrapper_path
    if wrapper.is_file():
        env = ", ".join(f"{key}={value}" for key, value in agent_wrapper_env(wrapper).items()) or "(none)"
        lines += [f"Wrapper:                              {wrapper}", f"Wrapper Env:                          {env}"]
    else:
        lines.append(f"Wrapper:                              {wrapper} (not written; fm schedule install writes it)")
    return "\n".join(lines)


MACOS = Backend(
    name="macos",
    scheduler="launchd",
    build_spec=functools.partial(ScheduleSpec.build, wrapper_suffix=MACOS_WRAPPER_SUFFIX),
    plan=render_agent_plan,
    install=install_agent,
    uninstall=uninstall_agent,
    show=show_agent,
)
"""This backend as ``fm schedule`` drives it."""

__all__ = [
    "AGENT_NOT_FOUND_MARKERS",
    "LABEL_PREFIX",
    "LAUNCHCTL",
    "LAUNCHD_LOG_FILENAME",
    "MACOS",
    "MACOS_WRAPPER_SUFFIX",
    "SHELL",
    "UNLOAD_WAIT_ATTEMPTS",
    "UNLOAD_WAIT_SECONDS",
    "WAKE_NOTE",
    "agent_label",
    "agent_wrapper_env",
    "current_uid",
    "install_agent",
    "is_agent_missing",
    "launch_agents_dir",
    "plist_path",
    "render_agent_plan",
    "render_launchctl_bootout",
    "render_launchctl_bootstrap",
    "render_launchctl_enable",
    "render_launchctl_print",
    "render_plist",
    "render_wrapper_sh",
    "show_agent",
    "uninstall_agent",
]
